openapi: 3.2.0
info:
  version: 1.0.0
  title: Other Accredited Representatives API
  description: This API provides access to accredited representatives based on various criteria such as location and type.
  contact:
    name: va.gov
servers:
- url: http://localhost:3000/services/veteran
  description: VA.gov API local environment
- url: https://staging-api.va.gov/services/veteran
  description: VA.gov API staging environment
- url: https://api.va.gov/services/veteran
  description: VA.gov API production environment
tags:
- name: Other Accredited Representatives
paths:
  /v0/other_accredited_representatives:
    get:
      summary: Get a list of accredited attorneys
      description: Retrieve accredited attorneys based on location, name, and type. Supports sorting and pagination.
      operationId: getOtherAccreditedRepresentatives
      tags:
      - Other Accredited Representatives
      parameters:
      - in: query
        name: lat
        required: true
        schema:
          type: number
          format: float
          minimum: -90
          maximum: 90
        description: Latitude for the search location.
      - in: query
        name: long
        required: true
        schema:
          type: number
          format: float
          minimum: -180
          maximum: 180
        description: Longitude for the search location.
      - in: query
        name: type
        required: true
        schema:
          type: string
        description: Type of accredited representative (e.g., attorney or claim_agents).
      - in: query
        name: distance
        schema:
          type: number
          format: integer
          enum:
          - 5
          - 10
          - 25
          - 50
          - 100
          - 200
        description: Search radius in miles.
      - in: query
        name: name
        schema:
          type: string
        description: Name to search for.
      - in: query
        name: page
        schema:
          type: integer
          default: 1
        description: Page number for pagination.
      - in: query
        name: per_page
        schema:
          type: integer
          default: 10
        description: Number of results per page.
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - distance_asc
          - first_name_asc
          - first_name_desc
          - last_name_asc
          - last_name_desc
          default: distance_asc
        description: Sorting order of the results.
      responses:
        '200':
          description: A list of accredited representatives
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseRepresentative'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    BadRequestError:
      type: object
      properties:
        errors:
          type: object
          properties:
            title:
              type: string
              example: Invalid field value
            detail:
              type: string
              example: my_rep is not a valid value for type
            code:
              type: string
              example: '103'
            status:
              type: string
              example: '400'
    InternalServerError:
      type: object
      properties:
        errors:
          type: object
          properties:
            title:
              type: string
              example: Internal server error
            detail:
              type: string
              example: Internal server error
            code:
              type: string
              example: '500'
            status:
              type: string
              example: '500'
